### ISSUE TITLE
wikipedia is showing a full page search !! 

### ISSUE THREAD

**Issue by Amrlol** [kalliope-project/kalliope_neuron_wikipedia#11]
hello everybody .
i'm having a small issue in showing the results of the wiki , kalliope shows a full page result , how can i make it show summary only ???? 

@Sispheor

**Comment by Sispheor** [comment]
sentences parameter?

**Comment by Amrlol** [comment]
i haven't changed the dafault value , which i think it was 10 !! 
how can i change it ?? @Sispheor

**Comment by Sispheor** [comment]
It's a neuron parameter, so just add it to your synapse.

**Comment by Amrlol** [comment]
thank alot , it's working correctely :+1:   @Sispheor
