### ISSUE TITLE
Ordre non reconnu

### ISSUE THREAD

**Issue by Riseryn** [kalliope-project/kalliope_neuron_wikipedia#13]
Bonjour,
je viens d'installer kalliope 0.6.0 et ce neuron qui semble être le seul compatible avec cette version; cependant, à chaque fois que je pose une question ( ex: recherche sur wikipedia avatar) j'ai la réponse suivante : Google Speech Recognition thinks you said recherche sur Wikipédia avatar
Je n'ai pas saisi cet ordre
d'où cela peut-il venir ?

**Comment by Sispheor** [comment]
Issue in English only.
For French support go on gitter chat. Link in the main readme.
