### ISSUE TITLE
Run a script with kalliope

### ISSUE THREAD

**Issue by okynvt** [kalliope-project/kalliope_neuron_wikipedia#7]
Hello I have a problem with calliope. I try to launch a script but it does not work.
here is the error 

" Google Speech Recognition thinks you said supervision
Order matched in the brain. Running synapse "run-script-1"
ERROR: Fail to execute neuron 'script'. Script not found or is not a file.. -> Execution skipped "

My file named "scripts.yml"
"---

  - name: "run-script-1"
    signals:
      - order: "lance la supervision"
      - order: "lancer la supervision"
      - order: "lance supervision"
      - order: "lancer supervision"
      - order: "supervision"

    neurons:
      - script:
          path: "/scripts/script1.sh"
          async: True
"

the script works, I tried to launch it from a shell and there is no problem

**Comment by Sispheor** [comment]
This is not the right palce to discuss about this. I'll close this ticket. 
FYI, there is a chat room link on the main readme of the project page.

To answer your question. The problem can be situated in a couple places:
- if the script id not placed in /scripts/script1.sh (this is an absolute path, be sure it exists)
- if the kalliope user doesn't have right on it
- if the script doesn't have the shebang line
- if the script is not executable from ACL (chmod +x)

**Comment by Sispheor** [comment]
[The chat room](https://gitter.im/kalliope-project/Lobby)
